// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassHide
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackageString = "b61984ec-1cec-4264-a4b3-bfe3f4b1bb1b";
        public static Guid guidVSPackage = new Guid(guidVSPackageString);

        public const string guidVSPackageCmdSetString = "9b24f905-69f7-446d-941a-427a2f4e0917";
        public static Guid guidVSPackageCmdSet = new Guid(guidVSPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CollapseAllCmdId = 0x0100;
    }
}