// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassHide
{
    internal sealed partial class Vsix
    {
        public const string Id = "ClassHide.b8c18253-f0aa-43d3-af54-3906483b20ad";
        public const string Name = "Class Hide";
        public const string Description = @"This extension collapses lengthy HTML class attributes, improving code readibility.";
        public const string Language = "en-US";
        public const string Version = "1.3.0";
        public const string Author = "Theron Wang";
        public const string Tags = "html, css, class, hide, collapse, readability, clutter, fold, utility, tailwind, tailwind css";
        public const bool IsPreview = false;
    }
}
