// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassHide
{
    internal sealed partial class Vsix
    {
        public const string Id = "ClassFold.b8c18253-f0aa-43d3-af54-3906483b20ad";
        public const string Name = "Class Fold";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Theron Wang";
        public const string Tags = "";
    }
}
